security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
           id: fos_user.user_provider.username

    firewalls:
    #    login:
    #        pattern: ^/login$
    #        anonymous:    true
    #    register:
    #        pattern: ^/register
    #        anonymous:    true
    #    forgot_password:
    #        pattern: ^/resetting/request
    #        anonymous:    true
    #    forgot_password:
    #        pattern: ^/resetting/send-email
    #        anonymous:    true
        main:
            pattern: ^/
            anonymous: ~
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider

    access_control:
        - { path: ^/profile$, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }