<?php

namespace Konani\CartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CartVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartVideoRepository extends EntityRepository
{
}
